# Generated by Django 3.1.4 on 2020-12-15 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('second_name', models.CharField(blank=True, default='', max_length=30)),
                ('birth_day', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('identity_card_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nationality', models.CharField(choices=[('Cmr', 'Cameroonian'), ('Oth', 'Others')], default='Cameroonian', max_length=255)),
                ('mobile_phone', models.IntegerField(unique=True)),
                ('picture', models.ImageField(upload_to='media/citizens_pictures')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'citizens',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Specialist', 'Specialist'), ('Generalist', 'Generalist')], max_length=10)),
                ('speciality', models.CharField(max_length=55, null=True)),
                ('mobile_phone_working', models.IntegerField(unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='HasScreened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('+', '+'), ('-', '-'), ('?', '?')], max_length=1)),
                ('screening_date', models.DateTimeField(auto_now=True)),
                ('type_screening', models.CharField(choices=[('quick', 'quick'), ('slow', 'slow')], max_length=5)),
                ('region', models.CharField(choices=[('Littoral', 'Littoral'), ('North', 'North'), ('North_West', 'North_West'), ('Centre', 'Centre'), ('South', 'South'), ('South_West', 'South_West'), ('East', 'East'), ('Adamaoua', 'Adamaoua'), ('Extreme_North', 'Extreme_North'), ('West', 'West')], max_length=13)),
                ('department', models.CharField(max_length=25)),
                ('quarter', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('site_following_him', models.CharField(max_length=255)),
                ('citizen_who_has_been_screened', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_who_has_been_screened', to='screening.citizen')),
            ],
            options={
                'db_table': 'has_screened',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('symptom_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=55)),
                ('text_explain', models.CharField(default='', max_length=2048)),
                ('illustration', models.FileField(null=True, upload_to='media')),
                ('value', models.IntegerField()),
                ('register_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'symptoms',
            },
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FreeWorker', 'FreeWorker'), ('Epidemiologist', 'Epidemiologist'), ('Doctor', 'Doctor')], max_length=14)),
                ('mobile_phone_working', models.IntegerField(unique=True)),
                ('citizens_tracked', models.ManyToManyField(related_name='citizens_tracked', through='screening.HasScreened', to='screening.Citizen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scouts',
            },
        ),
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
                ('comments', models.CharField(default='', max_length=1024)),
                ('result', models.CharField(default='', max_length=1024)),
                ('date_test', models.DateTimeField(auto_now=True)),
                ('citizen_who_has_been_tested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screening.citizen')),
                ('symptoms_detected', models.ManyToManyField(related_name='online_tests', to='screening.Symptom')),
            ],
            options={
                'db_table': 'online_tests',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('image', models.FileField(upload_to='media/news')),
                ('user_has_posted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.FileField(null=True, upload_to='media')),
                ('date_send', models.DateTimeField()),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user_has_written', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_has_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='hasscreened',
            name='scout_who_screened',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scout_info_tracker', to='screening.scout'),
        ),
        migrations.CreateModel(
            name='HasConsulted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consulted', models.DateField()),
                ('doctor_observation', models.CharField(default='', max_length=2048)),
                ('citizen_has_been_consulted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screening.citizen')),
                ('doctor_who_has_consulted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screening.doctor')),
            ],
            options={
                'db_table': 'has_consulted',
            },
        ),
    ]
