# Generated by Django 3.1.4 on 2020-12-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('West', 'West'), ('South_West', 'South_West'), ('North_West', 'North_West'), ('East', 'East'), ('South', 'South'), ('Adamaoua', 'Adamaoua'), ('Extreme_North', 'Extreme_North'), ('Littoral', 'Littoral'), ('Centre', 'Centre')], max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone_working',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
