# Generated by Django 3.1.4 on 2020-12-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_auto_20201215_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('South', 'South'), ('Centre', 'Centre'), ('Littoral', 'Littoral'), ('North', 'North'), ('South_West', 'South_West'), ('North_West', 'North_West'), ('East', 'East'), ('Extreme_North', 'Extreme_North'), ('West', 'West')], max_length=13),
        ),
    ]
