# Generated by Django 3.1.4 on 2020-12-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_auto_20201215_0031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Littoral', 'Littoral'), ('East', 'East'), ('Extreme_North', 'Extreme_North'), ('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('North', 'North'), ('West', 'West'), ('North_West', 'North_West'), ('South_West', 'South_West'), ('South', 'South')], max_length=13),
        ),
    ]
