# Generated by Django 3.1.4 on 2020-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_auto_20201222_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('North_West', 'North_West'), ('East', 'East'), ('North', 'North'), ('South', 'South'), ('West', 'West'), ('South_West', 'South_West'), ('Littoral', 'Littoral'), ('Extreme_North', 'Extreme_North')], max_length=13),
        ),
    ]
