# Generated by Django 3.1.4 on 2020-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_auto_20201215_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/citizens_pictures'),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('South_West', 'South_West'), ('Centre', 'Centre'), ('Extreme_North', 'Extreme_North'), ('North', 'North'), ('West', 'West'), ('North_West', 'North_West'), ('Littoral', 'Littoral'), ('East', 'East'), ('South', 'South'), ('Adamaoua', 'Adamaoua')], max_length=13),
        ),
    ]
