# Generated by Django 3.1.4 on 2020-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_auto_20201222_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('North_West', 'North_West'), ('West', 'West'), ('Littoral', 'Littoral'), ('South', 'South'), ('South_West', 'South_West'), ('Adamaoua', 'Adamaoua'), ('North', 'North'), ('Extreme_North', 'Extreme_North'), ('Centre', 'Centre'), ('East', 'East')], max_length=13),
        ),
    ]
