# Generated by Django 3.1.4 on 2020-12-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_auto_20201222_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('East', 'East'), ('North', 'North'), ('Littoral', 'Littoral'), ('Adamaoua', 'Adamaoua'), ('North_West', 'North_West'), ('West', 'West'), ('Extreme_North', 'Extreme_North'), ('South_West', 'South_West'), ('Centre', 'Centre'), ('South', 'South')], max_length=13),
        ),
    ]
