# Generated by Django 3.1.4 on 2020-12-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_auto_20201215_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizens_screened',
            field=models.ManyToManyField(through='screening.HasScreened', to='screening.Citizen'),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('North', 'North'), ('South_West', 'South_West'), ('Centre', 'Centre'), ('Littoral', 'Littoral'), ('Extreme_North', 'Extreme_North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('North_West', 'North_West')], max_length=13),
        ),
    ]
