# Generated by Django 3.1.4 on 2020-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0006_auto_20201217_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Extreme_North', 'Extreme_North'), ('East', 'East'), ('West', 'West'), ('Adamaoua', 'Adamaoua'), ('North_West', 'North_West'), ('South', 'South'), ('Littoral', 'Littoral'), ('South_West', 'South_West'), ('Centre', 'Centre'), ('North', 'North')], max_length=13),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='site_following_him',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
