# Generated by Django 3.1.4 on 2020-12-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0007_auto_20201217_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='identity_card_id',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='mobile_phone',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('South', 'South'), ('Littoral', 'Littoral'), ('Centre', 'Centre'), ('Adamaoua', 'Adamaoua'), ('North_West', 'North_West'), ('West', 'West'), ('South_West', 'South_West'), ('East', 'East'), ('Extreme_North', 'Extreme_North'), ('North', 'North')], max_length=13),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
