# Generated by Django 3.1.4 on 2020-12-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0007_auto_20201223_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Centre', 'Centre'), ('West', 'West'), ('South', 'South'), ('Extreme_North', 'Extreme_North'), ('North_West', 'North_West'), ('Littoral', 'Littoral'), ('Adamaoua', 'Adamaoua'), ('North', 'North'), ('East', 'East'), ('South_West', 'South_West')], max_length=13),
        ),
    ]
