# Generated by Django 3.1.4 on 2020-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('Littoral', 'Littoral'), ('Centre', 'Centre'), ('South_West', 'South_West'), ('Adamaoua', 'Adamaoua'), ('East', 'East'), ('North_West', 'North_West'), ('Extreme_North', 'Extreme_North'), ('South', 'South'), ('West', 'West')], max_length=13),
        ),
    ]
