# Generated by Django 3.1.4 on 2020-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_auto_20201222_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('South', 'South'), ('East', 'East'), ('Centre', 'Centre'), ('South_West', 'South_West'), ('Littoral', 'Littoral'), ('Extreme_North', 'Extreme_North'), ('North', 'North'), ('Adamaoua', 'Adamaoua'), ('North_West', 'North_West'), ('West', 'West')], max_length=13),
        ),
    ]
