# Generated by Django 3.1.4 on 2020-12-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0007_auto_20201223_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='age',
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('West', 'West'), ('North', 'North'), ('East', 'East'), ('Centre', 'Centre'), ('North_West', 'North_West'), ('South_West', 'South_West'), ('Littoral', 'Littoral'), ('Extreme_North', 'Extreme_North'), ('South', 'South'), ('Adamaoua', 'Adamaoua')], max_length=13),
        ),
    ]
