# Generated by Django 3.1.4 on 2020-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0008_auto_20201231_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Centre', 'Centre'), ('South_West', 'South_West'), ('North_West', 'North_West'), ('Littoral', 'Littoral'), ('Extreme_North', 'Extreme_North'), ('Adamaoua', 'Adamaoua'), ('South', 'South'), ('West', 'West'), ('East', 'East'), ('North', 'North')], max_length=13),
        ),
    ]
