# Generated by Django 3.1.4 on 2020-12-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0009_auto_20201231_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('South', 'South'), ('Adamaoua', 'Adamaoua'), ('Extreme_North', 'Extreme_North'), ('Littoral', 'Littoral'), ('West', 'West'), ('Centre', 'Centre'), ('North_West', 'North_West'), ('East', 'East'), ('South_West', 'South_West'), ('North', 'North')], max_length=13),
        ),
    ]
