# Generated by Django 3.1.4 on 2021-01-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0010_auto_20201231_0833'),
        ('screening', '0008_auto_20201225_1611'),
    ]

    operations = [
    ]
