# Generated by Django 3.1.1 on 2020-12-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_api_rest', '0002_auto_20201205_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Littoral', 'Littoral'), ('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('South', 'South'), ('South_West', 'South_West'), ('North', 'North'), ('Extreme_North', 'Extreme_North'), ('West', 'West'), ('North_West', 'North_West'), ('East', 'East')], max_length=13),
        ),
    ]
