# Generated by Django 3.1.1 on 2020-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_api_rest', '0004_auto_20201205_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('North_West', 'North_West'), ('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('South', 'South'), ('East', 'East'), ('South_West', 'South_West'), ('Littoral', 'Littoral'), ('West', 'West'), ('Extreme_North', 'Extreme_North')], max_length=13),
        ),
    ]
