# Generated by Django 3.1.1 on 2020-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_api_rest', '0005_auto_20201205_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='screened_date',
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('East', 'East'), ('South', 'South'), ('North_West', 'North_West'), ('South_West', 'South_West'), ('Littoral', 'Littoral'), ('Extreme_North', 'Extreme_North'), ('West', 'West'), ('North', 'North'), ('Adamaoua', 'Adamaoua'), ('Centre', 'Centre')], max_length=13),
        ),
    ]
