# Generated by Django 3.1.1 on 2020-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_api_rest', '0006_auto_20201205_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Centre', 'Centre'), ('West', 'West'), ('South_West', 'South_West'), ('North_West', 'North_West'), ('Adamaoua', 'Adamaoua'), ('East', 'East'), ('South', 'South'), ('Extreme_North', 'Extreme_North'), ('North', 'North'), ('Littoral', 'Littoral')], max_length=13),
        ),
    ]
