# Generated by Django 3.1.1 on 2020-12-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_api_rest', '0008_auto_20201205_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasscreened',
            old_name='citizen_who_has_screened',
            new_name='citizen_who_has_been_screened',
        ),
        migrations.RemoveField(
            model_name='hasconsulted',
            name='user_has_been_consulted',
        ),
        migrations.RemoveField(
            model_name='onlinetest',
            name='user_has_been_tested',
        ),
        migrations.AddField(
            model_name='hasconsulted',
            name='citizen_has_been_consulted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_api_rest.citizen'),
        ),
        migrations.AddField(
            model_name='onlinetest',
            name='citizen_who_has_been_tested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_api_rest.citizen'),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('West', 'West'), ('Centre', 'Centre'), ('East', 'East'), ('South_West', 'South_West'), ('Littoral', 'Littoral'), ('North_West', 'North_West'), ('Extreme_North', 'Extreme_North'), ('Adamaoua', 'Adamaoua'), ('South', 'South')], max_length=13),
        ),
    ]
