# Generated by Django 3.1.1 on 2020-12-05 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid_api_rest', '0010_auto_20201205_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 17, 18, 52, 944350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('South_West', 'South_West'), ('Littoral', 'Littoral'), ('Extreme_North', 'Extreme_North'), ('West', 'West'), ('South', 'South'), ('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('North_West', 'North_West'), ('East', 'East')], max_length=13),
        ),
    ]
