# Generated by Django 3.1.1 on 2020-12-05 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid_api_rest', '0011_auto_20201205_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='mobile_phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 17, 20, 9, 492365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile_phone_working',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hasscreened',
            name='region',
            field=models.CharField(choices=[('Extreme_North', 'Extreme_North'), ('North_West', 'North_West'), ('West', 'West'), ('North', 'North'), ('Centre', 'Centre'), ('South', 'South'), ('South_West', 'South_West'), ('East', 'East'), ('Adamaoua', 'Adamaoua'), ('Littoral', 'Littoral')], max_length=13),
        ),
        migrations.AlterField(
            model_name='scout',
            name='mobile_phone_working',
            field=models.IntegerField(unique=True),
        ),
    ]
