# Generated by Django 3.1.4 on 2020-12-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
